### ISSUE TITLE
Errors/warnings during install

### ISSUE THREAD

**Issue by elesueur** [vmware/api-explorer#73]
Hi Julia,

When installing this module, I encountered a number of issues. 

We are using angular 4.3.4 and Clarity 0.10.5.

elesueur@mediocre ~/test-ui % npm install apix-components --save
npm WARN saveError Problems were encountered
npm WARN saveError Please correct and try again.
npm WARN saveError peer invalid: @angular/common@4.3.0, required by apix-components@0.0.7
npm WARN saveError peer invalid: @angular/compiler@4.3.0, required by apix-components@0.0.7
npm WARN saveError peer invalid: @angular/core@4.3.0, required by apix-components@0.0.7
npm WARN saveError peer invalid: @angular/forms@4.3.0, required by apix-components@0.0.7
npm WARN saveError peer invalid: @angular/platform-browser@4.3.0, required by apix-components@0.0.7
npm WARN saveError peer invalid: @angular/platform-browser-dynamic@4.3.0, required by apix-components@0.0.7
npm WARN saveError peer invalid: @angular/router@4.3.0, required by apix-components@0.0.7
npm WARN saveError peer invalid: clarity-angular@0.10.10, required by apix-components@0.0.7
npm WARN saveError peer invalid: clarity-icons@0.10.10, required by apix-components@0.0.7
npm WARN saveError peer invalid: clarity-ui@0.10.10, required by apix-components@0.0.7
npm WARN saveError peer invalid: core-js@2.4.1, required by apix-components@0.0.7
npm WARN saveError peer invalid: zone.js@0.8.11, required by apix-components@0.0.7
npm WARN saveError peer invalid: swagger-ui@2.x, required by apix-components@0.0.7
npm WARN saveError peer invalid: jquery@^3.2.1, required by apix-components@0.0.7

All of the @angular and clarity peer dependencies should be more lenient.

Is there any chance we can do away with the jquery dependency?

**Comment by lijulia** [comment]
This has been resolved.
